### ISSUE TITLE
Add contributors guidelines

### ISSUE THREAD

**Issue by Cooper-Kunz** [hashgraph/hedera-proof-of-action-demo-pasteboard#2]
Can we showcase how folks can help support this application? Perhaps the Mirror Node [contributors guide](https://github.com/hashgraph/hedera-mirror-node/blob/master/CONTRIBUTING.md), but that may be a bit overkill for a demo.

**Comment by mehcode** [comment]
With #1 I called out that this project is "as-is". Demos are just that, demos. Folks are encouraged to clone and take it for a spin, but I wouldn't try to build on it more.
